---
name: provision the eks resources
on:
  workflow_dispatch:
    inputs:
      name:
        description: "target environment name"
        required: true
      destroy:
        description: "Destroy the resource"
        required: false
        default: false
jobs:
  deploy_source:
    name: terraform deployment
    runs-on: ubuntu-latest
    env:
      bucket: terraform-backend-buckets-tfn
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: eu-central-1

      - name: Init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.bucket }}" \
            -backend-config="key=${{ github.event.inputs.name }}/tfstate.tfstate" \
            -backend-config="region=eu-central-1" \
            -backend=true

      - name: Plan
        run: terraform  plan -var-file=config.tfvars

      - name: Apply
        run: terraform  apply -var-file=config.tfvars -auto-approve

      - name: Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform  destroy -var-file=config.tfvars -auto-approve
